apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.mysql.namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.mysql.secret.data }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}